### ISSUE TITLE
command 'scriptbox.runScript' not found in V8.0.0

### ISSUE THREAD

**Issue by WooodHead** [calebmpeterson/scriptbox#16]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/5668806/230770583-d46a4d28-d5ae-42b2-890d-b8e33d15ff69.png">

Command 'ScriptBox: Run Script' resulted in an error

command 'scriptbox.runScript' not found

**Comment by electrovir** [comment]
Same here. Strangely, when I first installed it earlier today it was working. Now it's not.

**Comment by electrovir** [comment]
Workaround: delete `~/.scriptbox`, then re-create your scripts. Now it's working 🤷 I assume it'll break again at some point in the future, but idk what the cause is.

**Comment by electrovir** [comment]
Just broke again for me for no apparent reason. So far nothing fixes it: reinstalling, deleting `~/.scriptbox`, etc.

**Comment by calebmpeterson** [comment]
@WooodHead / @electrovir are either of y'all still experiencing this bug? I'm on `8.3.0` and cannot reproduce.

**Comment by electrovir** [comment]
@calebmpeterson I'll try it out.

**Comment by electrovir** [comment]
A week later and I haven't had any issues! Last time the problem arose within a single day.

**Comment by calebmpeterson** [comment]
Thanks for checking @electrovir!
